### ISSUE TITLE
TWL/AGB was broken from last b9s-next branch nightly build

### ISSUE THREAD

**Issue by MelonGx** [astronautlevel2/Luma3DS#10]
I used to consider that was a Luma issue until someone told me he didn't have TWL/AGB issue by compiling the source code himself.
Latest master build is untested though.

**Comment by astronautlevel2** [comment]
Latest master branch should work, unfortunately I'm not in a position to test.

**Comment by MelonGx** [comment]
(Edit) Latest master branch is tested OK. Closing this issue.....
