### ISSUE TITLE
No new builds

### ISSUE THREAD

**Issue by Spodi** [astronautlevel2/Luma3DS#11]
I dont know if you are already aware, but there are no new builds since 901d499 (Jun 09, 2017).
Is your build env. broken?

**Comment by astronautlevel2** [comment]
I'm aware of the issue, it's likely due to an error in the SQL statement. Unfortunately I have finals and don't have time to try to find it until Wednesday probably, sorry.

**Comment by Spodi** [comment]
Oh, good luck with the finals then!

**Comment by srwgin** [comment]
only build on 6.18
now stop again
