### ISSUE TITLE
[Feature Request] Patch Freinds List to Prevent 3DS Updates

### ISSUE THREAD

**Issue by greenDarkness** [astronautlevel2/Luma3DS#14]
Hello there, 
Recently the friends list patch was removed from Luma3DS, and I was wondering if you'd consider adding it? Ctrhtpwn, and a few game mods don't work on the newer firmwares, and updating is necessary to play online games.
I think it would make a lot of users happy.
Thanks for all your work! I really like your Luma Builds!
https://github.com/AuroraWright/Luma3DS/commit/76f057dafbb7d1ad58afefe89c33ff316882cd44

**Comment by Hikari-chin** [comment]
The reasoning for removing it was explained in the comments on the commit. It will not be returned.

**Comment by astronautlevel2** [comment]
Hey,

This is simply a build site - my policy is not to modify upstream. There are a few reasons for this:

1. Modifying upstream with patches is a Herculean effort in that every single commit I'd need to apply, and possible change, the patch. I'm a fairly busy person so I have nowhere near the time needed for that.
2. If I modified upstream, this wouldn't be luma anymore, it'd be my own spin on it. I make builds of AuroraWright's Luma3DS, not my own variation. 

Out of curiosity, what game mods don't work on newer firmwares?

**Comment by greenDarkness** [comment]
Ah, I see. That's unfortunate, but I completely understand.

Yeah, one fellow spoke earlier about it being 16 lines of code, but I guess the real issue is maintaining since it has to be updated every time Nintendo puts out a new update.

I thought that your nightly Luma builds were modified? I guess that was my mistake. Your builds include a feature that tells you where the customfirmware is being booted; and I was pretty sure this feature wasn't in the official build.

I believe SuperOkazaki from the thread I linked would have a better explanation than the one I could  have given for the game patching; to be entirely honest, I don't know which mods to which he was referring. The main thing I was concerned with was friends who are on N3DS having to remove their back plate in order to modify their SD card.  Since Ctrhttpwn doesn't work about 11.3 like I mentioned above. 

Again, thanks so much for taking the time to respond to me.

**Comment by astronautlevel2** [comment]
That feature is in the latest commits of Luma3DS, but not in the latest stable. It will be present in the next stable release as well.

**Comment by greenDarkness** [comment]
Oh, well that explains it.

Have a good night!
