### ISSUE TITLE
Incorrect Builds/Versions for Luma3DS builds

### ISSUE THREAD

**Issue by cheatfreak47** [astronautlevel2/Luma3DS#2]
Third Time's the Charm indeed! x_x
Ehm.

As requested, I moved [StarUpdater Issue #15](https://github.com/astronautlevel2/StarUpdater/issues/15) to your website's github (correctly this time!) becase it's apparently a server side bug. ^_^

In your own words: 
"Probably something borked with lastVer checking. Either that or Aurora committed something weirdly and caused my (rather hacky) lastVer checking to fail.
I'll fix it manually for now and close this, I'd prefer this issue to be re-opened on my site's github."

**Comment by astronautlevel2** [comment]
This should be resolved now (?)
