### ISSUE TITLE
tried using the latest arm9loaderhax.bin from http://astronautlevel2.github.io/Luma3DS/

### ISSUE THREAD

**Issue by TheAzure289** [astronautlevel2/Luma3DS#3]
Tried to fix an online connectivity error by updating the arm9loaderhax.bin, my 2ds wouldn't boot so I went back to my old bin and now I'm stuck at the config screen. It will not save my choices, just refreshes without moving on.

**Comment by astronautlevel2** [comment]
I'll try to reproduce it.

**Comment by astronautlevel2** [comment]
Unable to reproduce, latest commit is the same as latest stable also. Try holding select when booting 6.1.2 and re-applying all your settings.
