### ISSUE TITLE
The "out" folder is empty, making it impossible to get the latest hourly

### ISSUE THREAD

**Issue by sks316** [astronautlevel2/Luma3DS#6]
When downloading the hourly, the "out" folder is empty, therefore making it impossible to get the latest hourly.

**Comment by astronautlevel2** [comment]
This is due to the fact that Luma has new build requirements.

Although this is a relatively simple fix, the bash script which runs this site is a horrible mess, so I'm going to rewrite it tomorrow.

**Comment by Shadow322** [comment]
"tomorrow" as in Sunday?

**Comment by Shadow322** [comment]
@astronautlevel2 wondering is it up yet or on another address?

**Comment by ghost** [comment]
He will probably close the issue when it's fixed.  You can always go to the website and check manually.

**Comment by MelonGx** [comment]
Hope that "tomorrow" will not become to "tomorrow(tm)"
(/me esc

**Comment by astronautlevel2** [comment]
Hey,

Unfortunately real life got in the way, though I have basically all of today to work uninterrupted. It'll probably be done tonight-ish.

**Comment by Dimensional** [comment]
Understood. So far I don't think you'll need to edit your script. Just need to include firmtool and it's dependencies into your build environment.

**Comment by astronautlevel2** [comment]
Strictly speaking, no, I don't _have_ to. However, I really really want to because the existing one is horrifying.

The script itself is a bunch of dirty bash hacks, but it's also literally a cronjob that checks out the entire repo and compares it to a stored version of the previous commit, and uses an HTML file as a way of keeping history of all the previous builds. The new system uses webhooks, so it should be substantially better (only building when there's an update, and building immediately when there's an update).

**Comment by astronautlevel2** [comment]
Okay, it's done and should be working now. I'll leave this issue open until there's 1-2 successful builds then close it.

The backend stuff is all on http://github.com/astronautlevel2/Luma3DS-Nightlies now.

**Comment by ghost** [comment]
The old urls to download the latest commit/stable release is no longer working.  Have they changed?
https://astronautlevel2.github.io/Luma3DS/latest.zip
https://astronautlevel2.github.io/Luma3DS/release.zip

**Comment by astronautlevel2** [comment]
I removed them, but if there's demand can add them back fairly easily

**Comment by KunoichiZ** [comment]
Hey, @astronautlevel2, I'm currently trying to edit Luma Updater to make it better and I'm getting reports of Luma Updater not downloading the hourly commit. The API URL listed in Luma Updater was [this](https://raw.githubusercontent.com/astronautlevel2/Luma3DS/gh-pages/lastCommit). Has this changed, and if it has, can you give the new link?

Thanks!

**Comment by astronautlevel2** [comment]
When I get home today (around 5ish EST probably) I can add it back.

**Comment by KunoichiZ** [comment]
Thank you so much!

**Comment by ghost** [comment]
Thank you.

**Comment by astronautlevel2** [comment]
I've re-added them manually for now, and will program it in again later today.

Also, a commit happened earlier that went fine, so I think it should be working.

**Comment by Shadow322** [comment]
@KunoichiZ doesn't seem like the betas r showing up in lumaupdater

**Comment by astronautlevel2** [comment]
Not my issue if something doesn't show up in Luma Updater, all I do is provide the file.

**Comment by KunoichiZ** [comment]
@astronautlevel2, do you know how to get the API link to the latest commit? I'm not sure what I need to change the link to to see if the hourlies work again.

**Comment by astronautlevel2** [comment]
It's at http://astronautlevel2.github.io/Luma3DS/latest.zip

**Comment by sks316** [comment]
So... Where they've always been?

**Comment by KunoichiZ** [comment]
The link in the Luma Updater code was not that link, @sks316.

**Comment by astronautlevel2** [comment]
Luma Updater did something weird with accessing the raw github file rather than the website file is probably why

**Comment by KunoichiZ** [comment]
Yeah it's really weird how that worked.

**Comment by KunoichiZ** [comment]
Okay, it's downloading the correct hourly now, but it's displaying "PK♥♦" as the latest hourly build name for some odd reason [(picture here)](https://imgur.com/a/UV6Ys). I may just disable the commit name.

**Comment by astronautlevel2** [comment]
Do you know how it gets the commit?

**Comment by KunoichiZ** [comment]
[Here](http://www.mediafire.com/file/zmhs747fqeb754z/release.cpp) is where it takes the link to the latest hourly.

**Comment by astronautlevel2** [comment]
It was actually relying on part of the hacked-together batch script to work, which is why now that it's been revised it won't. I can add that part back in manually however.

**Comment by astronautlevel2** [comment]
Also, moving this to a new issue
